server:
  port: 8080

spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        healthCheckPath: /hi
        healthCheckInterval: 60s
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  application:
    name: springboot-quartz

feign:
  hystrix:
    enabled: true

